# Generated by Django 4.1.3 on 2022-11-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(verbose_name='Last Maintenance Date'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='details',
            field=models.CharField(choices=[('R', 'Does not need maintenance'), ('M', 'Needs Further Maintenance'), ('O', 'Maintenance complete')], default='R', max_length=1),
        ),
    ]
