# Generated by Django 4.1.3 on 2022-11-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tires_alter_maintenance_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tires',
            old_name='color',
            new_name='hardness',
        ),
    ]
